name: Release

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: false
        default: 'main'
      version:
        description: 'Specify version'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Build Tools and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse3-dev \
            libcurl4-openssl-dev \
            build-essential \
            cmake \
            rpm \
            libboost-all-dev \
            nlohmann-json3-dev

      - name: Build and Test
        run: |
          ./build.sh
      
      - name: Package for Linux
        run: |
          ./package-deb.sh
          ./package-rpm.sh
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Tag triggering the workflow
          release_name: Release ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload `.deb` Package to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/*.deb
          asset_name: smfs_${{ github.ref_name }}.deb
          asset_content_type: application/x-deb

      - name: Upload `.rpm` Package to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/x86_64/*.rpm
          asset_name: smfs_${{ github.ref_name }}.rpm
          asset_content_type: application/x-rpm