name: Release

on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: false
        default: 'main'
      version:
        description: 'Specify version'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Build Tools and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse3-dev \
            libcurl4-openssl-dev \
            build-essential \
            cmake \
            rpm \
            libboost-all-dev \
            nlohmann-json3-dev \
            ca-certificates
            
      - name: Install `github-changelog-generator`
        run: |
          gem install --user-install github_changelog_generator
          # Add the local gem binary path to PATH
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
      
      - name: Generate Changelog
        env:
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt 
        run: |
          $HOME/.local/bin/github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${{ github.event.repository.name }} \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --output CHANGELOG.md
          
      - name: Build and Test
        run: |
          ./build.sh
      
      - name: Package for Linux
        run: |
          ./package-deb.sh
          ./package-rpm.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Use the tag triggering the workflow
          name: "Release ${{ github.ref_name }} (Tag: ${{ github.ref_name }})"
          body_path: CHANGELOG.md
          files: |
            build/*.deb
            build/x86_64/*.rpm
          draft: false
          prerelease: false
          fail_on_unmatched_files: true