name: Release

on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: false
        default: 'main'
      version:
        description: 'Specify version'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Install Build Tools and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfuse3-dev \
            libcurl4-openssl-dev \
            build-essential \
            cmake \
            rpm \
            libboost-all-dev \
            nlohmann-json3-dev
  
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Build and Test
        run: |
          ./build.sh
      
      - name: Package for Linux
        run: |
          ./package-deb.sh
          ./package-rpm.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Use the tag triggering the workflow
          name: "Release ${{ github.ref_name }} (Tag: ${{ github.ref_name }})"
          body: ${{steps.build_changelog.outputs.changelog}}
          files: |
            build/*.deb
            build/x86_64/*.rpm
          draft: false
          prerelease: false
          fail_on_unmatched_files: true